server:
  port: 18083

spring:
  application:
    name: order-service
  cloud:
    nacos:
      username: nacos
      password: 7fDJZBbiLzO2
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    name: storageDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seata?useSSL=false&serverTimezone=UTC
    username: root
    password: root1234

management:
  otlp:
    metrics:
      export:
        enabled: false
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info

seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: ${spring.application.name}-tx-group
  config:
    type: nacos
    nacos:
      serverAddr: 127.0.0.1:8848
      dataId: "seata.properties"
      group: SEATA_GROUP
      username: 'nacos'
      password: '7fDJZBbiLzO2'
  registry:
    type: nacos
    nacos:
      cluster: default
      group: SEATA_GROUP
      application: seata-server
      server-addr: 127.0.0.1:8848
      username: 'nacos'
      password: '7fDJZBbiLzO2'
