server:
  port: 18081

spring:
  application:
    name: business-service
  cloud:
    nacos:
      username: nacos
      password: 7fDJZBbiLzO2
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
    scheduling:
      distributed-mode: shedlock
  task:
    scheduling:
      thread-name-prefix: sca-schedule-
      pool:
        size: 5
      shutdown:
        await-termination: true
        await-termination-period: 60s
  datasource:
    driver-class: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:3306/seata?useSSL=false&serverTimezone=UTC
    username: root
    password: root1234

management:
  otlp:
    metrics:
      export:
        enabled: false
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

dubbo:
  application:
    name: ${spring.application.name}
    qos-port: 22230
  registry:
    id: nacos-registry
    address: nacos://${NACOS_SERVER_ADDR:127.0.0.1:8848}
    username: ${spring.cloud.nacos.username:nacos}
    password: ${spring.cloud.nacos.password:7fDJZBbiLzO2}
    parameters:
      group: DEFAULT_GROUP
  tracing:
    enabled: true

seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: ${spring.application.name}-tx-group
  config:
    type: nacos
    nacos:
      serverAddr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
      dataId: "seata.properties"
      group: SEATA_GROUP
      username: ${spring.cloud.nacos.username}
      password: ${spring.cloud.nacos.password}
  registry:
    type: nacos
    nacos:
      cluster: default
      group: SEATA_GROUP
      application: seata-server
      server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
      username: ${spring.cloud.nacos.username}
      password: ${spring.cloud.nacos.password}
