spring:
  application:
    name: consumer-dubbo-sample

dubbo:
  application:
    name: ${spring.application.name}
    qos-port: 22223
  protocol:
    name: tri
    port: -1
  registry:
    id: nacos-registry
    address: nacos://127.0.0.1:8848
    username: ${spring.cloud.nacos.username:nacos}
    password: ${spring.cloud.nacos.password:7fDJZBbiLzO2}
    parameters:
      group: DEFAULT_GROUP
  tracing:
    enabled: true

