server:
  port: 18080
spring:
  application:
    name: scheduling-sample
  task:
    scheduling:
      thread-name-prefix: sca-schedule-
      pool:
        size: 5
      shutdown:
        await-termination: true
        await-termination-period: 60s
  cloud:
    scheduling:
      distributed-mode: shedlock
  datasource:
    driver-class: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:3306/seata?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root1234
