spring:
  application:
    name: grpc-client-sample
  cloud:
    nacos:
      username: nacos
      password: 7fDJZBbiLzO2
      discovery:
        server-addr: 127.0.0.1:8848
    service-registry:
      auto-registration:
        enabled: false # 纯消费端关闭注册
  grpc:
    client:
      channel:
        default:
          target: discovery:///grpc-server-sample
