server:
  port: 8764
spring:
  application:
    name: demo-gateway
  cloud:
    nacos:
      username: nacos
      password: 7fDJZBbiLzO2
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true
    gateway:
      server:
        webflux:
          routes:
            - id: demo-consumer-reactive
              uri: lb://demo-consumer-reactive
              predicates:
                - name: Path
                  args:
                    pattern: /demo-consumer-reactive/**
              filters:
                - StripPrefix=1
            - id: demo-consumer
              uri: lb://demo-consumer
              predicates:
                - name: Path
                  args:
                    pattern: /demo-consumer/**
              filters:
                - StripPrefix=1
