server:
  port: 8768
spring:
  application:
    name: sentinel-gateway-sample
  cloud:
    nacos:
      username: nacos
      password: 7fDJZBbiLzO2
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true
    gateway:
      server:
        webflux:
          routes:
            - id: consumer-reactive-sample
              uri: lb://consumer-reactive-sample
              predicates:
                - name: Path
                  args:
                    pattern: /consumer-reactive-sample/**
              filters:
                - StripPrefix=1
            - id: consumer-sample
              uri: lb://consumer-sample
              predicates:
                - name: Path
                  args:
                    pattern: /consumer-sample/**
              filters:
                - StripPrefix=1
    sentinel:
      transport:
        dashboard: localhost:8081
      eager: true
      filter:
        enabled: true
      scg:
        order: -100
        fallback:
          mode: response
          response-status: 444
          response-body: '{"code":444,"msg":"Sentinel gateway block"}'
      datasource:
        ds1:
          file:
            file: classpath:gw-api-group.json
            data-type: json
            rule-type: gw-api-group
        ds2:
          file:
            file: classpath:gw-flow.json
            data-type: json
            rule-type: gw-flow

management:
  endpoint:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
