spring:
  application:
    name: provider-dubbo-sample

dubbo:
  application:
    name: ${spring.application.name}
    qos-port: 22222
  protocol:
    name: tri
    port: 50051
  registry:
    id: nacos-registry
    address: nacos://${NACOS_SERVER_ADDR:127.0.0.1:8848}
    username: ${spring.cloud.nacos.username:nacos}
    password: ${spring.cloud.nacos.password:7fDJZBbiLzO2}
    register-mode: instance
    parameters:
      group: DEFAULT_GROUP
  tracing:
    enabled: true

management:
  otlp:
    metrics:
      export:
        enabled: false
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info
